# -*- coding: utf-8 -*-
"""1-2 Operadores_e_variaveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LXpS2mk3-Mo3O1TQZeCSecq2XK_MUqTe

# Operadores Aritiméticos
"""

# Adição
10 + 2

# Subtração
10 - 2

# Multiplicação
10 * 2

# Divisão
10 / 2

# Divisão inteira
10 // 2

# Resto da divisão
10 % 2

# Potenciação
10 ** 2

"""# Operadores Relacionais"""

# Menor
10 < 2

# Menor ou igual
10 <= 2

# Maior
10 > 2

# Maior ou igual
10 >= 2

# Igual
7 == 7

# Diferente
7 != 7

"""# Operadores Lógicos



*   And
*   Or
*   Not

# Tabela verdade

And
"""

print(10 > 2 and 4 < 6)     # V and V == V
print(10 > 2 and 4 > 6)     # V AND F == F
print(10 < 2 and 4 < 6)     # F and V == F
print(10 < 2 and 4 > 6)     # F and F == F

"""Or"""

print(10 > 2 or 4 < 6)      # V or V == V
print(10 > 2 or 4 > 6)      # V or F == V
print(10 < 2 or 4 < 6)      # F or V == V
print(10 < 2 or 4 > 6)      # F or F == F

"""Not"""

not 10 > 2        # not V == F

not 10 < 2      # not F == V

"""# Variáveis

Variáveis estão alocadas em espaços na memória
"""

# Nome da varável é "x" que armazena o valor 10 em um espaço na memória
x = 10

print(x)

"""Regras

**Case Sensitive**

A != a

**Boas práticas com variáveis**


> Exemplo: Multiplicação de 2 números

Não usar

*   Multiplicação
*   MultiplicaçãoDeDoisNumeros
*   m

Usar

* multiplicacao
* mult
* mult_total (snake_case)

Tipos de variáveis

>Python é uma linguagem de alto nível

>Não é necessário especificar o tipo de dados quando declarar a variável

> Python define o tipo de dados na declaração
"""

num = 10      # Int (inteiro)

num = 10.5    # Float (real)

nome = "Rodrigo"  # String (Texto)

num = 10
print(num)
num = 10.5
print(num)

nome = 10
print(nome)
nome = "Rodrigo"
print(nome)