# -*- coding: utf-8 -*-
"""1-3 Interação com usuário.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vh2rte9x8HkwVagPH-jAYWiWLedbk85R

# Visualização de variáveis e textos
"""

print("Conhecendo o comando Print")

x = 8
print(x)

y = 10
soma = x + y
print(soma)

nome = 'Felipe Lancelotte'
print(nome)

"""Concatenação"""

x = 5
print('O valor de x é ', x)

print('O valor de x é ', x, 'e o dobro é', x * 2)

print('Eu,', nome, 'tirei', x, 'na prova de Python')

y = 10; z = 20 + x - y

print('Declarar várias variáveis na mesma linha:', y, z)

"""Type"""

x = 10
type(x)
print('x', type(x))

nome = "Felipe"
print('nome', type(nome))

num = '100'
num_convert = int(num)  # Converter variável
print('num', type(num))
print('num_convert', type(num_convert))

num_float = float(num)
print('num_float', num_float)

"""Input
* Armazenar a informação digitada pelo usuário em uma variável
* O dado armazenado sempre será um texto
"""

nome = input("Digite o nome do usuário ") #Aguardar o usuário digitar algo
print(nome)

nota = input("Digite a nota")

print(nome,', sua nota foi', nota)

valor = input('Digite o valor do produto: ')
print(valor)

# É necessário fazer a conversão da variável pois o imput salva como string
desconto = int(valor) - 5
print(desconto)

# É possível já definir o tipo da variável como numérico no momento do input
variavel_convertida = int(input('Digite um valor numérico '))
print(variavel_convertida + 2)