# -*- coding: utf-8 -*-
"""1-4 Estrutura condicional.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uFt5DNVqNZJEeXNga6Ci5eunM-2gm5nH

# Condicional
"""

# If
if 5 < 10:
  print('Verdadeiro')

# If/else
num1 = 10
num2 = 5
if num1 > num2:
  print('O num1 é maior')
else:
  print('O num2 é maior')

# If / Elif / Else
num1 = 10
num2 = 10
if num1 > num2:
  print('O num1 é o maior')
elif num1 < num2:
  print('O num2 é o maior')
else:
  print('Os dois são iguais')

"""# Condicional com operadores lógicos"""

num1 = 10
num2 = 5
num3 = 2
if (num1 > num2) and (num1 > num3):
  print('O num1 é o maior')
else:
  print('O num1 não é o maior')