# -*- coding: utf-8 -*-
"""1-5 Listas de valores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDBDYW14uAHXvpYWd0mmoKeTtyHZ-ZLt

## Listas, tuplas e dicionários
"""

# Lista
[1,2,3,4,5]

# Tupla
(1,2,3,4,5)

# Dicionário
{'num1': 1, 'num2': 2}

"""# Lista"""

lista = [4, "Felipe", 2.7]

type(lista)

lista.append("Lancelotte") # Adicionar um elemnto na lista

print(lista)
print(lista[1])

"""# Tupla"""

tupla = (4, 'Felipe', 2.7)

type(tupla)

tupla.append('Lancelotte')
# Não é possível adicionar elementos em uma tupla

# Este tipo de lista pode ser útil quando seu conjunto de elementos é
# estático e não se altera

print(tupla)

"""# Dicionário"""

dicionario = {'nome': 'Felipe', 'cidade': 'Rio de Janeiro'}

type(dicionario)

print(dicionario)

print(dicionario["nome"])

dicionario['ultimo_nome'] =  'Lancelotte'

print(dicionario)