# -*- coding: utf-8 -*-
"""1-6 Estrutura_de_repeticao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ObeTKzupUivfT2s5ELxqNH-dG8WIDtw2

# Estrutura de Repetição

## For
"""

# For Range
for contador in range(10):
  print(contador)

# For Range + Break
for contador in range(1000):
  print(contador)
  if contador == 2:
    break

lista = ['teste1', 'teste2']

# For simples
for val in lista:
  print(val)

# For com enumerate
for i, val in enumerate(lista):
  print(i, val)

"""## For com operadores compostos"""

lista2 = [2, 3, 4]

for val in lista2:
  val+= 1
  print(val)

for val in lista2:
  val *= 2
  print(val)

"""# While"""

val = 1
while (val < 6):
  val *= 2
  print(val)

# while com else
val = 1
while val < 10:
  val *= 2
else:
  print("O valor de val é: ", val)